// export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
// export const DELETE_TODO = 'DELETE_TODO';
// export const GET_TODO_SUCCESS = 'GET_TODO_SUCCESS';
// export const API_FAILURE = 'API_FAILURE';
// export const API_STARTED = 'API_STARTED';
export const SIGINTYPE = {
  SIGNUP_STARTED : 'SIGNUP_STARTED',
  SIGNUP_SUCCESS : 'SIGNUP_SUCCESS',
  SIGNUP_LOGOUT : 'SIGNUP_LOGOUT'
};

export const VERIFYOTP = {
  VERIFYOTP_STARTED : 'VERIFYOTP_STARTED',
  VERIFYOTP_SUCCESS : 'VERIFYOTP_SUCCESS'
};

export const UPDATEPROFILE = {
  UPDATEPROFILE_STARTED : 'UPDATEPROFILE_STARTED',
  UPDATEPROFILE_SUCCESS : 'UPDATEPROFILE_SUCCESS'
};

export const ONBOARDINGSTATUS = {
  STARTED:'ONBOARDING_STARTED',
  SUCCESS:'ONBOARDING_SUCCESS'
};

export const GETMESSAGELIST = {
  STARTED:'GETMESSAGELIST_STARTED',
  SUCCESS:'GETMESSAGELIST_SUCCESS'
};

export const READMESSAGE = {
  STARTED:'READMESSAGE_STARTED',
  SUCCESS:'READMESSAGE_SUCCESS'
};

export const GETNEWMESSAGE = {
  SUCCESS:'GETNEWMESSAGE_SUCCESS'
};

export const API_FAILURE = 'API_FAILURE';
